default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: raderj89
  password: "#!rongzhenjunx7786"

development:
  <<: *default
  database: tipster_development

test:
  <<: *default
  database: tipster_test

production:
  <<: *default
  database: tipster
  username: jared
  password: 123
