default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tipster_development

test:
  <<: *default
  database: tipster_test

production:
  <<: *default
  database: tipster
  username: jared
  password: 123
